# Generated by Django 4.2.14 on 2024-07-28 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenteeChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challenge_1", models.CharField(max_length=255)),
                (
                    "challenge_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "challenge_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "challenge_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "challenge_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField()),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
