# Generated by Django 4.2.14 on 2024-07-25 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admin_mentor_app", "0002_menteechallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="menteechallenge",
            name="mentor",
            field=models.ForeignKey(
                default="14",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="menteechallenge",
            name="mentee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
